// articles
export const GET_ARTICLES_LIST = 'GET_ARTICLES_LIST'
export const GET_ARTICLES_LIST_SUCCESS = 'GET_ARTICLES_LIST_SUCCESS'
export const GET_ARTICLES_LIST_FAILURE = 'GET_ARTICLES_LIST_FAILURE'
// charts
export const GET_CHARTS_LIST = 'GET_CHARTS_LIST'
export const GET_CHARTS_LIST_SUCCESS = 'GET_CHARTS_LIST_SUCCESS'
export const GET_CHARTS_LIST_FAILURE = 'GET_CHARTS_LIST_FAILURE'
// table
export const GET_TABLE_LIST = 'GET_TABLE_LIST'
export const GET_TABLE_LIST_SUCCESS = 'GET_TABLE_LIST_SUCCESS'
export const GET_TABLE_LIST_FAILURE = 'GET_TABLE_LIST_FAILURE'
